### ISSUE TITLE
Error converting OpenCvSharp.Mat to Emgu.CV.Mat

### ISSUE THREAD

**Issue by trittsv** [wingsziye/CSharpOpenCVLiberiesConverter#1]
`public static Emgu.CV.Mat MatOpenCVSharpToEmgu(OpenCvSharp.Mat opcvsMat)`

### Code
`OpenCvSharp.VideoCapture capture = new OpenCvSharp.VideoCapture(1);`
`OpenCvSharp.Mat frame = new OpenCvSharp.Mat();`
`capture.Read(frame);`
`Emgu.CV.Mat z = Emgu.CV.CvInvoke.CvArrToMat(frame.CvPtr, true); /* Error */`
### Error
Emgu.CV.Util.CvException
  HResult=0x80131500
  Nachricht = OpenCV: Unknown array type
  Quelle = Emgu.CV.World
  Stapelüberwachung:
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.CvInvoke.cveArrToMat(IntPtr cvArray, Boolean copyData, Boolean allowND, Int32 coiMode)
   at Emgu.CV.CvInvoke.CvArrToMat(IntPtr arr, Boolean copyData, Boolean allowND, Int32 coiMode)
   at ConsoleApp1.Program.Recognition() in C:\Users\sventrittler\documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 132
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\sventrittler\documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 37

### Versions
- EMGU.CV 3.4.3.3016
- OpenCvSharp3-AnyCPU 3.4.4.20181118

**Comment by wingsziye** [comment]
you can try like this

```
OpenCvSharp.VideoCapture capture = new OpenCvSharp.VideoCapture(1);
OpenCvSharp.Mat frame = new OpenCvSharp.Mat();
capture.Read(frame);
var emguMat = new Emgu.CV.Mat();
Emgu.CV.CvInvoke.Imdecode(frame.ToBytes(), ImreadModes.AnyColor, emguMat);
return emguMat;

```
It works.`
